francoismassart/eslint-plugin-tailwindcss

- .vscode/settings.json
- lib/config/groups.js
- lib/index.js
- lib/rules/classnames-order.js
- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
- lib/util/ast.js
- lib/util/attr.js
- lib/util/docsUrl.js
- lib/util/groupMethods.js
- lib/util/removeDuplicatesFromArray.js
- tests/lib/rules/classnames-order.js
- tests/lib/rules/no-contradicting-classname.js
- tests/lib/rules/no-custom-classname.js
This PR allows you to parse `TemplateLiteral` string used as argument in a `CallExpression`.
The callee's name must be whitelisted, the default config accepts `ctl` aka the tiny utility [classnames-template-literals](https://github.com/netlify/classnames-template-literals) from netlify.
You can specify one or more callee names by setting the `callees` option which expects an array of strings.
**Only works for the `classnames-order` rule for now**
FIXES
- [BUG] Single quotes are replaced by double quotes #4
MINOR
- Formatted code using Prettier
- Refact
- `schema` meta
`npm test`
> ADD support for `CallExpression` (e.g. `ctl(...)`)

- lib/config/groups.js
- tests/lib/rules/no-custom-classname.js
Fixes a bug where this plugin treated the tailwind class `self-end` as a custom class.
See: https://tailwindcss.com/docs/align-self
* OS + version: MacOS Big Sur
* NPM version: 6.4.12
* Node version: 14.16.1
> Fix error on Align Self (self-end)

- lib/util/groupMethods.js
Fix syntax error of `config.theme[propName]?.[k]`
The error was a syntax one, so i just run the script
* OS + version: macOS 11.2.3
* NPM version: 7.14.0
* Node version: 15.12.0
> Fix theme object access

- lib/rules/no-custom-classname.js
- lib/util/plugin.js
- tests/lib/rules/no-custom-classname.js
This PR adds support for recognizing [custom utilities](https://tailwindcss.com/docs/plugins#adding-utilities) as whitelist classnames for `no-custom-classname` rule.
**Only works on custom utilities and does not support other custom plugins**
`npm test`
> Add support for custom utilities

- docs/rules/classnames-order.md
- lib/rules/classnames-order.js
- lib/util/settings.js
- tests/lib/rules/classnames-order.js
Reading the thread from @adamwathan about [the best way to structure your classes and markup with Tailwind CSS](https://threadreaderapp.com/thread/1399473267606528005.html) I though people might want to 
> Group responsive classes together by screen size (...)
setting the option `groupByResponsive` to `true` will do just that and then within each responsive variant group, it'll order classnames as you would expect.
Fixes #30 
- `npm test`
> feat(classnames-order): group by responsive variant

- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
I noticed that the rules are spending a lot of time doing group generation, which seems to be a good candidate for improving the performance of the rules. I tried moving the generation out of the hot code paths, which seems to have improved the performance tremendously, especially for the `no-custom-classname` rule.
Running my eslint config on my repository resulted in the following timings, before and after these changes have been applied. As you see, both of the changed rules have fallen out of the "after" chart, meaning that it's no longer a part of the top 10 slowest rules.
**Before:**
```
❯ TIMING=1 yarn lint
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
tailwindcss/no-custom-classname         | 31050.121 …
```
> Performance gains on `no-custom-classname` and `no-contradicting-classname`

- lib/rules/classnames-order.js
- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
- lib/util/settings.js
- tests/lib/rules/classnames-order.js
- tests/lib/rules/no-contradicting-classname.js
- tests/lib/rules/no-custom-classname.js
I've added support for validating the rules against tagged templates. This means you could now validate e.g. ```const styles = myTag`block px-4`;```
Most of the code is copy-paste from the `CallExpression` implementations, so there could be potential for code de-duplication/refactoring here.
I've duplicated some of the tests you've added for validating `CallExpression`s (`ctl(...)` & `clsx(...)`) and adjusted them to `TaggedTemplateExpression`s instead.
> feat: add support for tagged templates

- lib/index.js
Currently causes `ESLint couldn't find the plugin "eslint-plugin-tailwind".`
I must admit, I have not tested it, as it's simply a one word fix on a regression. Let me know if you'd like me to run anything.
> Fix using incorrect plugin

- docs/rules/no-custom-classname.md
Add `cssFiles` option and use correct rule name. I suppose this was a copy and paste from another rule's docs but the code sample was not updated.
> Fix `no-custom-classname` sample code

- lib/util/attr.js
- tests/lib/rules/classnames-order.js
> fix: trailing spaces

- lib/util/groupMethods.js
- tests/lib/rules/classnames-order.js
Feel free to edit/close/etc.
Correctly handle number values in config.
Given this Tailwind config:
```ts
module.exports = {
theme: {
zIndex: {
dialog: 10000,
},
}
}
```
The lint task fails with
```
TypeError: Error while loading rule 'tailwindcss/no-contradicting-classname': val.indexOf is not a function
```
Test is included in the PR
- [-] I have made corresponding changes to the documentation
> fix: correctly handle number values in config

- lib/util/groupMethods.js
- package-lock.json
- package.json
- tests/lib/rules/no-custom-classname.js
Fixes #100 Using parentheses in the class name causes an error in the "tailwindcss/no-custom-classname" rule
Fixes #101 Using the percent symbol in square brackets of the class name causes an error in the "tailwindcss/no-custom-classname" rule
> FIXES for `no-custom-classname`

- lib/rules/classnames-order.js
- lib/rules/enforces-shorthand.js
- lib/rules/migration-from-tailwind-2.js
- lib/rules/no-arbitrary-value.js
- lib/util/ast.js
- tests/lib/rules/classnames-order.js
- tests/lib/rules/enforces-shorthand.js
- tests/lib/rules/migration-from-tailwind-2.js
- tests/lib/rules/no-arbitrary-value.js
- tests/lib/rules/no-contradicting-classname.js
- tests/lib/rules/no-custom-classname.js
Added cases for crawling `ArrayExpression` elements and `ObjectExpression` keys to each recursive parse function.
Fixes #99
Added unit tests for each rule covering class names in arrays and objects.
* OS + version: macOS Catalina
* NPM version: 8.1.0
* Node version: 16.13.0
> fix: crawl arrays and objects passed to callees

- lib/rules/classnames-order.js
- lib/util/groupMethods.js
This PR speeds up `tailwindcss/enforces-shorthand` and `tailwindcss/classnames-order` with `officialSorting: true` by introducing `WeakMap` caches to reduce duplicate calculations.
Since I cannot test this on @ronny1020's code base, I'm not sure if #136 can be marked as fixed with this PR. In particular, I also tried finding low-hanging fruit to optimise `tailwindcss/classnames-order` with `officialSorting: false`, but I couldn't find anything that would significantly speed things up.
I've timed the `tailwindcss/*` rules using a minimal `.eslintrc` file on my code base (which I can't share, unfortunately).
```
$ TIMING=1 node --inspect ./node_modules/.bin/eslint .
$ time node --inspect ./node_modules/.bin/eslint .
```
Full details on the …
> #136: Speed up execution time with caches

- lib/util/ast.js
- tests/lib/rules/no-contradicting-classname.js
- tests/lib/rules/no-custom-classname.js
In the fuction `parseNodeRecursive` of `lib/util/ast.js`, the case for TemplateListeral nodes would always recurse over `exp.right` for all expressions in the template. However, these expressions are not necessarily binary expressions. Removing the `.right` will make sure that e.g. ConditionalExpressions are also checked.
I've added a test to `tests/lib/rules/no-custom-classname.js` and `tests/lib/rules/no-contradicting-classname.js`.
* OS + version: Arch Linux (last upgraded today)
* NPM version: 8.5.5
* Node version: 16.14.2
> Fix `parseNodeRecursive`: Correctly recurse into TemplateLiteral expressions

- lib/rules/classnames-order.js
- lib/rules/enforces-negative-arbitrary-values.js
- lib/rules/enforces-shorthand.js
- lib/rules/migration-from-tailwind-2.js
- lib/rules/no-arbitrary-value.js
- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
- tests/lib/rules/classnames-order.js
- tests/lib/rules/enforces-negative-arbitrary-values.js
- tests/lib/rules/enforces-shorthand.js
- tests/lib/rules/migration-from-tailwind-2.js
- tests/lib/rules/no-arbitrary-value.js
- tests/lib/rules/no-contradicting-classname.js
- tests/lib/rules/no-custom-classname.js
Prevent `<div class></div>` from crashing.
Fixes #157
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
tests/lib/rules/classnames-order.js
tests/lib/rules/enforces-negative-arbitrary-values.js
tests/lib/rules/enforces-shorthand.js
tests/lib/rules/migration-from-tailwind-2.js
tests/lib/rules/no-arbitrary-value.js
tests/lib/rules/no-contradicting-classname.js
tests/lib/rules/no-custom-classname.js
* macOS Monterey
* npm 8.5.5
* node v16.14.2
> Prevent rule crash from class/className shorthand while typing.

- lib/rules/no-contradicting-classname.js
- tests/lib/rules/no-contradicting-classname.js
FIX: Conflicting rules with arbitrary values
This changes the algorithm on the rule `lib/rules/no-contradicting-classname.js`, to detect conflicting rules when using ambiguous arbitrary values.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
I've added a test to tests/lib/rules/no-contradicting-classname.js.
* OS + version: macOS monterey
* NPM version: 6.14.11
* Node version: v14.16.0
> FIX: Conflicting rules with ambiguous arbitrary values

- lib/rules/classnames-order.js
- lib/rules/enforces-negative-arbitrary-values.js
- lib/rules/enforces-shorthand.js
- lib/rules/no-arbitrary-value.js
- lib/util/ast.js
- tests/lib/rules/classnames-order.js
- tests/lib/rules/enforces-shorthand.js
- tests/lib/rules/no-arbitrary-value.js
- tests/lib/rules/no-contradicting-classname.js
- tests/lib/rules/no-custom-classname.js
This plugin offers support for [classnames](https://www.npmjs.com/package/classnames), a widely used package. But this package handles keys as classnames. This is different then any other plugin like [CVA](https://github.com/joe-bell/cva). 
PR contains a check if the callee is from classnames. Maybe not the best check but only classnames plugin handles this different, so I think it is valid to check for this specific callee. 
Fixes #135
Added two tests in no-custom-className based on custom callee
* OS + version: e.g. macOS Mojave
* NPM version: 16.14.2
* Node version: 8.5
> feat: Support for Object syntax in custom callees beside `classnames`

- lib/util/ast.js
- tests/lib/rules/classnames-order.js
Simple change to change the class-identifying regex to `/^class(Name)?$|^tw$`
NOTE: though unlikely it is possible that a codebase is already using the `tw` prop. For this reason it might make more sense to make this an opt-in config option called `props`, similar to `tags`.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
- duplicated a few tests on classnames-order rule and replaced the class` prop with `tw`
* OS + version: macOS Monterey
* NPM version: `8.11.0`
* Node version: `v16.16.0`
- No, they do when using props called `tw`
> Add support for `tw` prop from Twin

- .gitignore
- README.md
- docs/rules/classnames-order.md
- docs/rules/enforces-negative-arbitrary-values.md
- docs/rules/enforces-shorthand.md
- docs/rules/migration-from-tailwind-2.md
- docs/rules/no-arbitrary-value.md
- docs/rules/no-contradicting-classname.md
- docs/rules/no-custom-classname.md
- lib/rules/classnames-order.js
- lib/rules/enforces-negative-arbitrary-values.js
- lib/rules/enforces-shorthand.js
- lib/rules/migration-from-tailwind-2.js
- lib/rules/no-arbitrary-value.js
- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
- lib/util/ast.js
- lib/util/settings.js
- tests/lib/rules/classnames-order.js
Adds a custom classRegex option in line with to support external libraries like [twin.macro](https://github.com/ben-rogerson/twin.macro). The option name is in line with the option of the [Official Tailwind CSS IntelliSense VSCode plugin](https://github.com/tailwindlabs/tailwindcss/issues/7553).
This PR was based on @finnmerlett earlier work.
```json5
{
settings: {
tailwindcss: {
classRegex: "^class(Name)?$" // can be modified to support custom attributes. E.g. "^tw$" for `twin.macro`
},
},
}
```
> Add support for custom classRegex option in addition to class and className

- README.md
- package.json
Moves `tailwindcss` to in [./package.json](./package.json) from `dependencies` to:
- `devDependencies` - for developing & testing the plugin
- and to `peerDependencies`, so the projects which use your awesome plugin can install `tailwindcss` on their own, with a certain version.
The installation instructions in the [./README.md](./README.md) also got updated.
There is no need for testing this, AFAIK.
> chore:  Move `tailwindcss` to `devDependency` & `peerDependency`

- lib/rules/classnames-order.js
- lib/rules/enforces-negative-arbitrary-values.js
- lib/rules/enforces-shorthand.js
- lib/rules/migration-from-tailwind-2.js
- lib/rules/no-arbitrary-value.js
- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
- lib/util/ast.js
- package-lock.json
- package.json
- tests/lib/rules/no-custom-classname.js
Fixes #216 
- [xI have performed a self-review of my own code
> fix: #216 `classRegex` ignored in vuejs

- docs/rules/classnames-order.md
- docs/rules/enforces-negative-arbitrary-values.md
- docs/rules/enforces-shorthand.md
- docs/rules/migration-from-tailwind-2.md
- docs/rules/no-arbitrary-value.md
- docs/rules/no-contradicting-classname.md
- docs/rules/no-custom-classname.md
- lib/rules/classnames-order.js
- lib/rules/enforces-negative-arbitrary-values.js
- lib/rules/enforces-shorthand.js
- lib/rules/migration-from-tailwind-2.js
- lib/rules/no-arbitrary-value.js
- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
- lib/util/ast.js
- lib/util/settings.js
- package-lock.json
- package.json
- tests/lib/rules/no-custom-classname.js
- Add a new setting `ignoredKeys`
- Add `cva` to the default list of `callees`
- Add tests for this new `ignoredKeys` setting
Fixes #193 
Tests added in `no-custom-classname`
> feat: add `ignoredKeys` in settings

- lib/util/ast.js
- lib/util/prettier/order.js
- tests/lib/rules/classnames-order.js
- tests/lib/rules/no-custom-classname.js
Fixes #245
This PR improves interpretation of space-separated class names to match the web standards.
Currently any space character `\s` was treated as class separators. However, according to the [relevant spec](https://dom.spec.whatwg.org/#concept-getelementsbyclassname) only [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace) should be treated as separators.
See a concrete example and the motivation in the issue.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
* OS + version: macOS
* NPM version: 9.5.1
* Node version: 19.8.1
> fix: do not handle non-ASCII whitespace as separator

- lib/util/ast.js
- tests/lib/rules/no-custom-classname.js
The code inside `ast.js` previously assumed that properties of an `ObjectExpression` ast node would always be a `Property` node, but the spec also allows them to be a `SpreadExpression` ([See here](https://github.com/typescript-eslint/typescript-eslint/blob/3f97eb554a0d928152344f59913f798fd4517b13/packages/ast-spec/src/unions/ObjectLiteralElement.ts#L4))
Fixes #250
I added a test case with a spread expression inside the `className` property.
As expected this test failed, throwing "TypeError: Cannot read properties of undefined (reading 'type')". After modifying the code inside `ast.js`, this test now passes.
> fix: Parsing spreads in object expressions

- lib/rules/enforces-shorthand.js
- tests/lib/rules/enforces-shorthand.js
This PR aims to enforce that `overflow-hidden text-ellipsis whitespace-nowrap` can be replaced with the `truncate` class.
Fixes #253
I added unit-test cases, which should extensively test the newly introduced code.
> feat: Support enforcing `truncate` shorthand

- README.md
- lib/config/groups.js
- package-lock.json
- package.json
- tests/lib/rules/no-contradicting-classname.js
> fix: bg-center mark as conflicting with bg-[image:xxx]

- .github/pull_request_template.md
- .github/workflows/build.yml
- CONTRIBUTING.md
- package.json
Adds a workflow so that tests are run automatically.
Build
You can see the test run on my fork: https://github.com/nihalgonsalves/eslint-plugin-tailwindcss/actions/runs/7356169530/job/20025897805
> ci: add github actions workflow

- lib/util/ast.js
- tests/lib/rules/classnames-order.js
Similarly to https://github.com/francoismassart/eslint-plugin-tailwindcss/pull/251 spreading function return values inside of `clsx` call or similar fails with `TypeError: Cannot read properties of undefined (reading 'type')`
This is a simple fix to simply ignore those nodes.
Fixes # (issue)
I added a test that matches my minimal reproduction. It fails without the introduced change.
* OS + version: e.g. macOS Mojave
* NPM version: ...
* Node version: ...
> fix: Parsing spreads in function call returns

- lib/rules/enforces-shorthand.js
- tests/lib/rules/enforces-shorthand.js
I noticed a small bug when updating a side project to `eslint-plugin-tailwindcss@3.14.0` and running `pnpm fix:eslint`. See commit history in https://github.com/kachkaev/website/pull/311.
**Input:**
```jsx
<body className={`relative flex h-full w-full flex-col overflow-y-scroll px-5 pt-4 ${locale}`}>
```
**Ouput:**
```jsx
<body className={`relative flex size-full flex-col overflow-y-scroll px-5 pt-4${locale}`}>
```
**Expected output:**
```jsx
<body className={`relative flex size-full flex-col overflow-y-scroll px-5 pt-4 ${locale}`}>
```
This PR makes sure that a space is not removed between `pt-4` and `${locale}` when `tailwindcss/enforces-shorthand` does an autofix.
See new unit tests
CI
- ~~I have made corresponding …
> Fix edge cases with whitespace in `enforces-shorthand`

- .gitignore
- README.md
- lib/config/flat-recommended.js
- lib/config/recommended.js
- lib/config/rules.js
- lib/index.js
- lib/util/parser.js
- package-lock.json
- package.json
- tests/integrations/flat-config.js
- tests/integrations/flat-config/.npmrc
- tests/integrations/flat-config/a.vue
- tests/integrations/flat-config/eslint.config.js
- tests/integrations/flat-config/package.json
- tests/integrations/legacy-config.js
- tests/integrations/legacy-config/.eslintrc
- tests/integrations/legacy-config/.npmrc
- tests/integrations/legacy-config/a.vue
- tests/integrations/legacy-config/package.json
- tests/lib/index.js
- tests/lib/rules/no-custom-classname.js
Fixes #280 
This PR supports flat config.
It is also compatible with existing configs.
- OS + version: macOS Ventura 13.2.1
- NPM version: v10.2.5
- Node version: v18.19.1
> feat: support flat config

- lib/util/cssFiles.js
- tests/lib/rules/no-custom-classname.js
Reduced both sync IO time and reduced js performance overhead
Fixes #276 
- OS + version: Windows 11
- NPM version: 10.5.0
- Node version: 20.12.0
> no-custom-classname: perf optimization

- lib/util/ast.js
- package-lock.json
- tests/lib/rules/no-custom-classname.js
Fix a TypeError exception for null expressions in the AST.
While linting my application, exceptions about the AST are raised in some components:
```
TypeError: Cannot read properties of null (reading 'type') Occurred while linting /app/src/components/TestComponent.vue:47 Rule: "vue/attributes-order"
at isArrayExpression (/app/node_modules/eslint-plugin-tailwindcss/lib/util/ast.js:99:92)
at isVueValidAttributeValue (/app/node_modules/eslint-plugin-tailwindcss/lib/util/ast.js:121:10)
at Object.isValidVueAttribute (/app/node_modules/eslint-plugin-tailwindcss/lib/util/ast.js:184:8)
```
Apparently the `VExpressionContainer` can pass all the checks, but the value for `expression` is `null`. This modification makes sure it is not treated as an object that can be passed onward.
Linting fails on …
> fix ast expression tests for null expressions

- lib/util/ast.js
- package.json
- tests/lib/rules/no-custom-classname.js
This PR fixes an issue occurring with the `no-custom-classname` rule, where it did not detect custom classes inside *object in list* patterns:
`<div :class="[{'custom-not-detected': true}]"/>`.
Fixes #319 
New tests have been added. They're all using vue-eslint-parser in a .vue file.
- Testing for invalid/valid classes when using object within list
- Testing with a mix of valid/invalid within the object, and with classes written directly in the array.
- Testing with multiple objects and classes between them, in an array.
- OS + version: macOS Sequoia 15.0 (24A335)
- NPM version: 10.8.3
- Node version: 22.6.0
---
- VSCode with TS automatically removed some unreachable code.
- I added a check in the ast util, it's working well as all tests passed, but I don't know if …
> Fix custom classnames rule with VueJS objects within list.

- lib/config/rules.js
- lib/rules/classnames-order.js
- lib/rules/enforces-negative-arbitrary-values.js
- lib/rules/enforces-shorthand.js
- lib/rules/migration-from-tailwind-2.js
- lib/rules/no-arbitrary-value.js
- lib/rules/no-contradicting-classname.js
- lib/rules/no-custom-classname.js
- lib/rules/no-unnecessary-arbitrary-value.js
- lib/util/customConfig.js
- lib/util/getSortedClassNamesWorker.js
- lib/util/getTailwindConfigWorker.js
- lib/util/groupMethods.js
- lib/util/isValidClassNameWorker.js
- lib/util/settings.js
- lib/util/tailwindAPI.js
- package-lock.json
- package.json
- tests/lib/rules/arbitrary-values.js
- tests/lib/rules/no-custom-classname.js
- tests/lib/util/groupMethods.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
- OS + version: e.g. macOS Mojave
- NPM version: ...
- Node version: ...
> feat: support tailwind v4
